DECLARE
  PROCEDURE GET_TEACHERS (PCODE TEACHER.PULPIT%TYPE) IS
    CURSOR teacher_cur IS 
      SELECT TEACHER_NAME 
      FROM TEACHER 
      WHERE PULPIT = PCODE;
  BEGIN
    DBMS_OUTPUT.PUT_LINE('Преподаватели кафедры ' || PCODE || ':');
    FOR teacher_rec IN teacher_cur LOOP
      DBMS_OUTPUT.PUT_LINE(teacher_rec.TEACHER_NAME);
    END LOOP;
  END GET_TEACHERS;
BEGIN
  DBMS_OUTPUT.ENABLE;
  GET_TEACHERS('ИСиТ');
END;
/

DECLARE
  FUNCTION GET_NUM_TEACHERS (PCODE TEACHER.PULPIT%TYPE) RETURN NUMBER IS
    var_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO var_count
    FROM TEACHER
    WHERE PULPIT = PCODE;
    RETURN var_count;
  END GET_NUM_TEACHERS;
BEGIN
  DBMS_OUTPUT.ENABLE;
  DBMS_OUTPUT.PUT_LINE('Количество преподавателей на кафедре ИСиТ: ' || 
                       GET_NUM_TEACHERS('ИСиТ'));
END;
/

DECLARE
  PROCEDURE GET_TEACHERS (FCODE FACULTY.FACULTY%TYPE) IS
    CURSOR teacher_cur IS 
      SELECT TEACHER.TEACHER_NAME
      FROM TEACHER
      INNER JOIN PULPIT ON TEACHER.PULPIT = PULPIT.PULPIT
      WHERE PULPIT.FACULTY = FCODE;
  BEGIN
    DBMS_OUTPUT.PUT_LINE('Преподаватели факультета ' || FCODE || ':');
    FOR teacher_rec IN teacher_cur LOOP
      DBMS_OUTPUT.PUT_LINE(teacher_rec.TEACHER_NAME);
    END LOOP;
  END GET_TEACHERS;
BEGIN
  DBMS_OUTPUT.ENABLE;
  GET_TEACHERS('ИДиП');
END;
/

DECLARE
  PROCEDURE GET_SUBJECTS (PCODE SUBJECT.PULPIT%TYPE) IS
    CURSOR subject_cur IS 
      SELECT SUBJECT_NAME
      FROM SUBJECT
      WHERE PULPIT = PCODE;
  BEGIN
    DBMS_OUTPUT.PUT_LINE('Дисциплины кафедры ' || PCODE || ':');
    FOR subject_rec IN subject_cur LOOP
      DBMS_OUTPUT.PUT_LINE(subject_rec.SUBJECT_NAME);
    END LOOP;
  END GET_SUBJECTS;
BEGIN
  DBMS_OUTPUT.ENABLE;
  GET_SUBJECTS('ИСиТ');
END;
/

DECLARE
  FUNCTION GET_NUM_TEACHERS (FCODE FACULTY.FACULTY%TYPE) RETURN NUMBER IS
    var_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO var_count
    FROM TEACHER
    INNER JOIN PULPIT ON TEACHER.PULPIT = PULPIT.PULPIT
    WHERE PULPIT.FACULTY = FCODE;
    RETURN var_count;
  END GET_NUM_TEACHERS;
BEGIN
  DBMS_OUTPUT.ENABLE;
  DBMS_OUTPUT.PUT_LINE('Количество преподавателей на факультете ИДиП: ' || 
                       GET_NUM_TEACHERS('ИДиП'));
END;
/

DECLARE
  FUNCTION GET_NUM_SUBJECTS (PCODE SUBJECT.PULPIT%TYPE) RETURN NUMBER IS
    var_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO var_count
    FROM SUBJECT
    WHERE PULPIT = PCODE;
    RETURN var_count;
  END GET_NUM_SUBJECTS;
BEGIN
  DBMS_OUTPUT.ENABLE;
  DBMS_OUTPUT.PUT_LINE('Количество дисциплин на кафедре ИСиТ: ' || 
                       GET_NUM_SUBJECTS('ИСиТ'));
END;
/

CREATE OR REPLACE PACKAGE TEACHERS AS
  PROCEDURE GET_TEACHERS (FCODE FACULTY.FACULTY%TYPE);
  PROCEDURE GET_SUBJECTS (PCODE SUBJECT.PULPIT%TYPE);
  FUNCTION GET_NUM_TEACHERS (FCODE FACULTY.FACULTY%TYPE) RETURN NUMBER;
  FUNCTION GET_NUM_SUBJECTS (PCODE SUBJECT.PULPIT%TYPE) RETURN NUMBER;
END TEACHERS;
/

CREATE OR REPLACE PACKAGE BODY TEACHERS AS
  PROCEDURE GET_TEACHERS (FCODE FACULTY.FACULTY%TYPE) IS
    CURSOR teacher_cur IS 
      SELECT TEACHER.TEACHER_NAME
      FROM TEACHER
      INNER JOIN PULPIT ON TEACHER.PULPIT = PULPIT.PULPIT
      WHERE PULPIT.FACULTY = FCODE;
  BEGIN
    DBMS_OUTPUT.PUT_LINE('Преподаватели факультета ' || FCODE || ':');
    FOR teacher_rec IN teacher_cur LOOP
      DBMS_OUTPUT.PUT_LINE(teacher_rec.TEACHER_NAME);
    END LOOP;
  END GET_TEACHERS;
  
  PROCEDURE GET_SUBJECTS (PCODE SUBJECT.PULPIT%TYPE) IS
    CURSOR subject_cur IS 
      SELECT SUBJECT_NAME
      FROM SUBJECT
      WHERE PULPIT = PCODE;
  BEGIN
    DBMS_OUTPUT.PUT_LINE('Дисциплины кафедры ' || PCODE || ':');
    FOR subject_rec IN subject_cur LOOP
      DBMS_OUTPUT.PUT_LINE(subject_rec.SUBJECT_NAME);
    END LOOP;
  END GET_SUBJECTS;
  
  FUNCTION GET_NUM_TEACHERS (FCODE FACULTY.FACULTY%TYPE) RETURN NUMBER IS
    var_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO var_count
    FROM TEACHER
    INNER JOIN PULPIT ON TEACHER.PULPIT = PULPIT.PULPIT
    WHERE PULPIT.FACULTY = FCODE;
    RETURN var_count;
  END GET_NUM_TEACHERS;
  
  FUNCTION GET_NUM_SUBJECTS (PCODE SUBJECT.PULPIT%TYPE) RETURN NUMBER IS
    var_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO var_count
    FROM SUBJECT
    WHERE PULPIT = PCODE;
    RETURN var_count;
  END GET_NUM_SUBJECTS;
END TEACHERS;
/

BEGIN
  DBMS_OUTPUT.ENABLE;
  
  TEACHERS.GET_TEACHERS('ИДиП');
  DBMS_OUTPUT.PUT_LINE('----------------');
  TEACHERS.GET_SUBJECTS('ИСиТ');
  DBMS_OUTPUT.PUT_LINE('----------------');
  DBMS_OUTPUT.PUT_LINE('Количество преподавателей на ИДиП: ' || 
                       TEACHERS.GET_NUM_TEACHERS('ИДиП'));
  DBMS_OUTPUT.PUT_LINE('Количество дисциплин на ИСиТ: ' || 
                       TEACHERS.GET_NUM_SUBJECTS('ИСиТ'));
END;
/