CREATE TABLE T_RANGE (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(50)
)
PARTITION BY RANGE (id) (
    PARTITION p1 VALUES LESS THAN (100),
    PARTITION p2 VALUES LESS THAN (200),
    PARTITION p3 VALUES LESS THAN (300)
);

CREATE TABLE T_INTERVAL (
    id NUMBER PRIMARY KEY,
    event_date DATE
)
PARTITION BY RANGE (event_date) (
    PARTITION p1 VALUES LESS THAN (TO_DATE('04-04-2025', 'DD-MM-YYYY')),
    PARTITION p2 VALUES LESS THAN (TO_DATE('05-04-2025', 'DD-MM-YYYY')),
    PARTITION p3 VALUES LESS THAN (TO_DATE('06-04-2025', 'DD-MM-YYYY'))
);

CREATE TABLE T_HASH (
    id NUMBER PRIMARY KEY,
    code VARCHAR2(10)
)
PARTITION BY HASH (code) (
    PARTITION p1,
    PARTITION p2,
    PARTITION p3
);

CREATE TABLE T_LIST (
    id NUMBER PRIMARY KEY,
    region CHAR(2)
)
PARTITION BY LIST (region) (
    PARTITION p1 VALUES ('BY', 'RU'),
    PARTITION p2 VALUES ('UK'),
    PARTITION p3 VALUES ('US')
);

INSERT INTO T_RANGE VALUES (50, 'Item 1');
INSERT INTO T_RANGE VALUES (150, 'Item 2');
INSERT INTO T_RANGE VALUES (250, 'Item 3');
COMMIT;

SELECT id, name, TABLE_NAME, PARTITION_NAME 
FROM USER_TAB_PARTITIONS 
INNER JOIN T_RANGE ON 1=1 
WHERE TABLE_NAME = 'T_RANGE';

INSERT INTO T_INTERVAL VALUES (1, TO_DATE('04-04-2025', 'DD-MM-YYYY'));
INSERT INTO T_INTERVAL VALUES (2, TO_DATE('04-03-2025', 'DD-MM-YYYY'));
INSERT INTO T_INTERVAL VALUES (3, TO_DATE('04-02-2025', 'DD-MM-YYYY'));
COMMIT;

SELECT id, event_date, TABLE_NAME, PARTITION_NAME 
FROM USER_TAB_PARTITIONS 
INNER JOIN T_INTERVAL ON 1=1 
WHERE TABLE_NAME = 'T_INTERVAL';

INSERT INTO T_HASH VALUES (1, 'ABC');
INSERT INTO T_HASH VALUES (2, 'DEF');
INSERT INTO T_HASH VALUES (3, 'GHI');
COMMIT;

SELECT id, code, TABLE_NAME, PARTITION_NAME 
FROM USER_TAB_PARTITIONS 
INNER JOIN T_HASH ON 1=1 
WHERE TABLE_NAME = 'T_HASH';

INSERT INTO T_LIST VALUES (1, 'BY');
INSERT INTO T_LIST VALUES (2, 'RU');
INSERT INTO T_LIST VALUES (3, 'US');
COMMIT;

SELECT id, region, TABLE_NAME, PARTITION_NAME 
FROM USER_TAB_PARTITIONS 
INNER JOIN T_LIST ON 1=1 
WHERE TABLE_NAME = 'T_LIST';

ALTER TABLE T_RANGE ENABLE ROW MOVEMENT;
UPDATE T_RANGE SET id = 175 WHERE id = 50;
SELECT * FROM T_RANGE PARTITION (p1);
SELECT * FROM T_RANGE PARTITION (p2);

ALTER TABLE T_INTERVAL ENABLE ROW MOVEMENT;
UPDATE T_INTERVAL SET event_date = TO_DATE('15-02-2025', 'DD-MM-YYYY') WHERE id = 1;
SELECT * FROM T_INTERVAL PARTITION (p1);
SELECT * FROM T_INTERVAL PARTITION (p2);

ALTER TABLE T_HASH ENABLE ROW MOVEMENT;
UPDATE T_HASH SET code = 'XYZ' WHERE id = 1;
SELECT * FROM T_HASH PARTITION (p1);
SELECT * FROM T_HASH PARTITION (p2);

ALTER TABLE T_LIST ENABLE ROW MOVEMENT;
UPDATE T_LIST SET region = 'US' WHERE id = 1;
SELECT * FROM T_LIST PARTITION (p1);
SELECT * FROM T_LIST PARTITION (p2);
SELECT * FROM T_LIST PARTITION (p3);

ALTER TABLE T_RANGE 
MERGE PARTITIONS p1, p2 INTO PARTITION p_merged;

SELECT * FROM USER_TAB_PARTITIONS WHERE TABLE_NAME = 'T_RANGE';

ALTER TABLE T_LIST 
SPLIT PARTITION p1 INTO (
    PARTITION p1a VALUES ('RU'),
    PARTITION p1b
);

SELECT * FROM USER_TAB_PARTITIONS WHERE TABLE_NAME = 'T_LIST';

CREATE TABLE T_HASH_TEMP (
    id NUMBER PRIMARY KEY,
    code VARCHAR2(10)
);

INSERT INTO T_HASH_TEMP VALUES (4, 'TEMP');
COMMIT;

ALTER TABLE T_HASH 
EXCHANGE PARTITION p1 WITH TABLE T_HASH_TEMP;

SELECT * FROM T_HASH PARTITION (p1);

SELECT * FROM T_HASH_TEMP;

SELECT TABLE_NAME 
FROM USER_PART_TABLES;

SELECT PARTITION_NAME 
FROM USER_TAB_PARTITIONS 
WHERE TABLE_NAME = 'T_RANGE';

SELECT * FROM T_LIST PARTITION (p1a);

SELECT * FROM T_LIST WHERE id < 100;