SELECT TABLESPACE_NAME, CONTENTS FROM DBA_TABLESPACES;

SELECT FILE_NAME, TABLESPACE_NAME FROM DBA_DATA_FILES   
UNION ALL
SELECT FILE_NAME, TABLESPACE_NAME FROM DBA_TEMP_FILES;

SELECT GROUP#, THREAD#, SEQUENCE#, STATUS FROM V$LOG;

SELECT GROUP# FROM V$LOG WHERE STATUS = 'CURRENT';

SELECT GROUP#, MEMBER FROM V$LOGFILE;

ALTER SYSTEM SWITCH LOGFILE;
SELECT CURRENT_SCN FROM V$DATABASE;

ALTER DATABASE ADD LOGFILE GROUP 4 
('\DB\ORADATA\FREE\REDO04a.LOG', 
 '\DB\ORADATA\FREE\REDO04b.LOG', 
 '\DB\ORADATA\FREE\REDO04c.LOG') SIZE 50M;
 
SELECT * FROM V$LOG;

ALTER SYSTEM SWITCH LOGFILE;
SELECT CURRENT_SCN FROM V$DATABASE;

ALTER SYSTEM CHECKPOINT;

ALTER DATABASE DROP LOGFILE GROUP 4;

SELECT LOG_MODE FROM V$DATABASE;

SELECT MAX(SEQUENCE#) FROM V$ARCHIVED_LOG;

ALTER SYSTEM ARCHIVE LOG CURRENT;
SELECT SEQUENCE#, NAME FROM V$ARCHIVED_LOG;
SELECT CURRENT_SCN FROM V$DATABASE;

SHOW PARAMETER CONTROL_FILES;
    
ALTER DATABASE BACKUP CONTROLFILE TO TRACE;

SHOW PARAMETER USER_DUMP_DEST;
