SELECT ROWID, id, name FROM MDS_T1;

SHOW PARAMETER spfile;

CREATE PFILE = 'MDS_PFILE.ORA' FROM SPFILE;

CREATE SPFILE = 'mds_spfile.ora' FROM PFILE = 'MDS_PFILE.ORA';

SELECT * FROM V$PARAMETER WHERE name = 'pga_aggregate_target';

ALTER SYSTEM SET pga_aggregate_target=512M SCOPE=BOTH;

SHOW PARAMETER control;

ALTER DATABASE BACKUP CONTROLFILE TO TRACE;