SELECT * FROM USER_DB_LINKS;

CREATE TABLE REMOTE_TABLE (
    ID NUMBER PRIMARY KEY,
    str VARCHAR2(50)
);

INSERT INTO REMOTE_TABLE (ID, str) VALUES (1, 'test1');
INSERT INTO REMOTE_TABLE (ID, str) VALUES (2, 'test2');
COMMIT;

CREATE OR REPLACE PROCEDURE REMOTE_PROC AS
BEGIN
    INSERT INTO REMOTE_TABLE (ID, str) VALUES (3, 'test3');
    COMMIT;
END;