ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE TABLESPACE TS_MDS
DATAFILE 'TS_MDS.dbf'
SIZE 7M
AUTOEXTEND ON NEXT 5M
MAXSIZE 30M;

CREATE TEMPORARY TABLESPACE TS_MDS_TEMP
TEMPFILE 'TS_MDS_TEMP.dbf'
SIZE 5M
AUTOEXTEND ON NEXT 3M
MAXSIZE 20M;

SELECT TABLESPACE_NAME, STATUS FROM DBA_TABLESPACES;

SELECT TABLESPACE_NAME, FILE_NAME, BYTES/1024/1024 AS SIZE_MB FROM DBA_DATA_FILES
UNION ALL
SELECT TABLESPACE_NAME, FILE_NAME, BYTES/1024/1024 AS SIZE_MB FROM DBA_TEMP_FILES;

CREATE ROLE RL_MDSCORE;

GRANT CREATE TABLE,
      CREATE SESSION,
      CREATE VIEW,
      CREATE PROCEDURE TO MDSCORE;

SELECT * FROM DBA_ROLES WHERE ROLE = 'RL_MDSCORE';

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'RL_MDSCORE';

CREATE PROFILE PF_MDSCORE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 3
    FAILED_LOGIN_ATTEMPTS 7
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;

SELECT * FROM DBA_PROFILES WHERE PROFILE = 'PF_MDSCORE';

CREATE USER MDSCORE IDENTIFIED BY 123
DEFAULT TABLESPACE TS_MDS QUOTA UNLIMITED ON TS_MDS
TEMPORARY TABLESPACE TS_MDS_TEMP
PROFILE PF_MDSCORE
ACCOUNT UNLOCK
PASSWORD EXPIRE;

SELECT value FROM v$parameter WHERE name = 'service_names';

ALTER USER MDSCORE QUOTA 2M ON TS_MDS;

ALTER TABLESPACE TS_MDS ONLINE;


