CREATE TABLESPACE TS_MDS_PDB
DATAFILE 'TS_MDS_PDB.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE ROLE ROLE_MDS;
GRANT CONNECT, RESOURCE TO ROLE_MDS;


CREATE PROFILE PROFILE_MDS LIMIT
    FAILED_LOGIN_ATTEMPTS 5
    PASSWORD_LIFE_TIME 90
    PASSWORD_REUSE_TIME 180
    PASSWORD_LOCK_TIME 1;
    
CREATE USER U1_MDS_PDB IDENTIFIED BY Password
DEFAULT TABLESPACE TS_MDS_PDB
PROFILE PROFILE_MDS
QUOTA UNLIMITED ON TS_MDS_PDB;

GRANT ROLE_MDS TO U1_MDS_PDB;
GRANT CREATE SESSION TO U1_MDS_PDB;
GRANT CREATE TABLE TO U1_MDS_PDB;
GRANT CREATE VIEW TO U1_MDS_PDB;
GRANT CREATE PROCEDURE TO U1_MDS_PDB;
GRANT CREATE TRIGGER TO U1_MDS_PDB;









